# Use Python image
FROM python:3.9-slim

# Set environment variables for security
ENV PYTHONUNBUFFERED 1

# Install necessary dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the project files into the container
COPY . /app

# Set the working directory
WORKDIR /app

# Command to run the application
CMD ["python", "src/python/ml_pipeline.py"]
